- topic_name: "/clock"
  ros_type_name: "rosgraph_msgs/msg/Clock"
  gz_type_name: "ignition.msgs.Clock"
  direction: "GZ_TO_ROS"

- ros_topic_name: "/joint_states"
  gz_topic_name: "/world/my_world/model/marauder/joint_state"
  ros_type_name: "sensor_msgs/msg/JointState"
  gz_type_name: "ignition.msgs.Model"
  direction: "GZ_TO_ROS"

- topic_name: "/cmd_vel"
  ros_type_name: "geometry_msgs/msg/Twist"
  gz_type_name: "ignition.msgs.Twist"
  direction: "ROS_TO_GZ"

- ros_topic_name: "/tf"
  gz_topic_name: "/model/marauder/pose"
  ros_type_name: "tf2_msgs/msg/TFMessage"
  gz_type_name: "ignition.msgs.Pose_V"
  direction: "GZ_TO_ROS"

- ros_topic_name: "/camera"
  gz_type_name: "ignition.msgs.Image"
  ros_type_name: "sensor_msgs/msg/Image"
  direction: "GZ_TO_ROS"

- ros_topic_name: "/lidar"
  gz_type_name: "ignition.msgs.LaserScan"
  ros_type_name: "sensor_msgs/msg/LaserScan"
  direction: "GZ_TO_ROS"

- ros_topic_name: "/depth_camera/points"
  gz_type_name: "ignition.msgs.PointCloudPacked"
  ros_type_name: "sensor_msgs/msg/PointCloud2"
  direction: "GZ_TO_ROS"

- ros_topic_name: "/depth_camera"
  gz_type_name: "ignition.msgs.Image"
  ros_type_name: "sensor_msgs/msg/Image"
  direction: "GZ_TO_ROS"
