<?xml version="1.0"?>
<robot xmlns:xacro="http://www.ros.org/wiki/xacro">

    <gazebo>
        <plugin name="skid_steer_drive" filename="libgazebo_ros_diff_drive.so">
            <ros>
                <namespace>/</namespace>
                <argument>cmd_vel:=/cmd_vel</argument>
                <argument>odom:=/odom</argument>
            </ros>
            <update_rate>100.0</update_rate>

            <!-- Number of wheel pairs -->
            <num_wheel_pairs>2</num_wheel_pairs>

            <!-- wheels1-->
            <left_joint>front_left_joint</left_joint>
            <right_joint>front_right_joint</right_joint>


            <wheel_separation>${wheel_separation}</wheel_separation>

            <wheel_diameter>${wheel_radius * 2}</wheel_diameter>

            <robot_base_frame>base_footprint</robot_base_frame>
            <!-- limits -->
            <max_wheel_torque>20</max_wheel_torque>
            <max_wheel_acceleration>1.0</max_wheel_acceleration>

            <!-- output -->
            <publish_odom>true</publish_odom>
            <publish_odom_tf>true</publish_odom_tf>
            <publish_wheel_tf>true</publish_wheel_tf>
        </plugin>
    </gazebo>

</robot>